### PR TITLE
Jlw patches

### LINKED ISSUE #2: NerdStash tokenizer is not found on fresh install.
Initialization fails with System.IO.FileNotFoundException when trying to locate the nerdstash_tokenizer.json file.

### LINKED ISSUE #3: .NET 8.0 support.
now that .NET 8.0 is out, the project could be updated to use it with very few changes. This might be a good idea since 8.0 is a long-term-support (LTS) release, so will be maintained by Microsoft longer.

### LINKED ISSUE #4: auth.json does not serialize correctly with .NET 8
since AuthConfig is a struct and Auth.cs is using JsonSerializer from System.Text.Json instead of Newtonsoft, the auth.json file writes an empty JSON object when serializing. 

This only occurs if the file does not already exist, or if only the username and password are defined, and the AuthEnv() method tries to serialize the EncryptionKey and AccessKey values.

### LINKED ISSUE #5: Ability to programmatically initialize Authorization without relying on the auth.config file
It would be useful to be able to initialize a NovelAPI instance with the NewNovelAiAPI factory method without relying on the auth.json file. 

This could be accomplished by passing in a nullable AuthConfig value to the method that would be used to initiallize the instance. If no value were passed in, then the code could fall back to using the auth.json file.

If the method were set to initialize the AuthConfig parameter to null, then the new method would be 100% backwards compatible with existing code.

### LINKED ISSUE #6: NovelAPI.csproj could be set to automatically copy the encoder.json and vocab.bpe files to the bin config directories.
It is possible to set up the csproj file to automatically copy the files to the output directory on build.

### PR DESCRIPTION
**Pull request by JasonLWalker**
Patches to resolve some of the Issues/Feature requests I reported:

Resolves: #3
Resolves: #4 
Resolves: #5 
Resolves: #2 
Resolves: #6 

I also updated to the nerdstash_tokenizer_v2.json

### CODE REVIEW

**Comment by Draco18s** [comment]
Oh damn, someone who cares about this and isn't me.

Good stuff, dude. A bunch of it is helper-utility that I just didn't bother with (e.g. nerdstash_tokenizer, as I had to figure out what tokenizer they were using and then locate the sucker, and then update the code to make sure it was accurate, at which point I didn't need to write a fetch method).

**Comment by Draco18s** [comment]
Pulled all of that in, had a few local changes that needed resolving but it was pretty much two "no that's fine, why's that a conflict."

I am reverting my local project back to .NET 7, as it caused a bunch of errors likely related to packages (I love it when VS tells me it can't find `string`). I know I had trouble getting the encryption package to play nice, and I think my dependent project might not cleanly update to .NET 8; I'd have to check and it isn't a priority for me.

Good stuff, thanks!

**Comment by JasonLWalker** [comment]
LOL, yeah, I've got several things I'm working on, so I'll probably add
some more pull requests soon for the audio and image generation  portions
of the WebAPI.

**Comment by Draco18s** [comment]
I haven't looked into the image gen side of things yet. The "more priority" items for me would be the stories, lorebook, etc. But my current usage manages its own versions of those things.

Hence the "here's other endpoint urls" comment.

**Comment by JasonLWalker** [comment]
Gotcha. BTW, my email address is jason@draxjinn.com if you want to contact me directly. I'd love to continue contributing code, but don't want to duplicate things you are currently working on. I also have a lot of experience creating NuGet packages, and automating the GitHub build process for NuGet releases, so it would be possible to release this library package as a NuGet package. (Which makes it easier to include in other projects without directly including the code.)

**Comment by Draco18s** [comment]
Oh, you aren't stepping on any toes updating things here, for what I'm doing the API is complete-enough. Only reason I muck about in this solution is when I am missing a feature I actually need. For instance, wanting the newer LLM model, because Euterpe was too dumb.

**Pull request merged**
